# Chapter 9 Exception Handling

Book: Java a beginner’s guide

## Why should we handle exceptions (runtime errors)

- It enables your program to respond to an error and then continue running
- In JS code, if any exception occurs in the call stack, all the functions in the call stack are removed
- Angular has the default error handler in place, therefore if an exception occurs, the error handler would catch it and console.log the error
- With IOS code, exceptions cause the native app to crash and close automatically
- In java, when an exception is thrown, it must be caught by some piece of code. If your program doesn’t catch an exception, it will be caught by JVM. The JVM’s default exception handler terminates execution and displays a stack trace and error message.

## The Exception Hierarchy

- In java, all exceptions are represented by classes, which are derived from a class Throwable
- When an exception occurs in a program, an object of some type of exception class is generated
- Two direct subclasses of Throwable: Error and Exception (errors that result from program activity, such as devided-by-zero, array boundary, and file errors)
- An important subclass of Exception is RuntimeException, which is used to represent various common types of run-time errors

## Exception Handling Fundamentals

- Java exception handling is managed via 5 keywords: try, catch, throw, throws, and finally
- Try: code that you want to monitor for exceptions are contained within a try block. If an exception occurs within the try block, it is thrown.
- Catch: your code can catch this exception (to ensure the app is not crashed) using catch and handle it in some rational manner
- Finally: Any code that must be executed upon existing from a try block is put in a finally block
- System-generated exceptions are automatically thrown by the java run-time system
- To manually throw an exception, use the keyword throw
- There can be more than one catch statement associated with a try. The type of the exception determines which catch statement is executed
- All code within a try block is monitored for exceptions, this includes exceptions that are generated by a method called from within the try block
- Order of execution:

1. With an exception occurs: try -> catch -> finally
2. No exception occurs: try -> finally

- Once an exception has been handled, it is removed from the system.
- If you want to catch exceptions of both a superclass type and a subclass type, put the subclass first in the catch sequence (similar to if…else if…else, the order matters)
- Add a catch clause that catches exceptions of type Exception is equivalent to adding a “catch all” clause to your exception handler
- Try blocks can be nested. An exception generated within the inner try block that is not caught by a catch associated with the inner try is propagated to the outer try block.
- Use the outer try block jot catch the most severe errors, allowing inner try blocks to handle less serious ones
